name: C/C++ CI

on:
  push:
    branches: [ master, kolobok ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd Chat; make clean; make
